/**
 * Sandbox Executor Worker Types
 * For executing Claude tasks via AI Gateway and Cloudflare Sandbox
 */

// Re-export Env from generated worker-configuration.d.ts
// The Env interface is auto-generated by `wrangler types` and includes:
// - Sandbox: DurableObjectNamespace<Sandbox>
// - CONFIG_SERVICE_URL: string
// - MAX_EXECUTION_TIME: string
// Additional properties not in wrangler.toml need to be declared here

// Extend the generated Env with secrets and optional bindings
export interface Env extends Cloudflare.Env {
  // AI Gateway auth token (for SDK mode)
  CF_AIG_TOKEN?: string;

  // Anthropic API key (for Sandbox mode - passed to container)
  ANTHROPIC_API_KEY?: string;

  // Optional: Instance ID override
  DEFAULT_INSTANCE_ID?: string;

  // Optional: Rate Limiter Durable Object (for Phase 2)
  // RATE_LIMITER?: DurableObjectNamespace;
}

/**
 * Request to execute a task in the sandbox (CLI mode)
 */
export interface ExecuteRequest {
  // The task/prompt to send to Claude Agent
  task: string;

  // Optional: Git repository to clone and work on
  repo?: string;

  // Optional: Instance ID for multi-tenant scenarios
  instance_id?: string;

  // Optional: Project ID for tracking
  project_id?: string;

  // Optional: Execution options
  options?: ExecuteOptions;
}

/**
 * Options for task execution (Sandbox/CLI approach)
 */
export interface ExecuteOptions {
  // Maximum execution time in ms (default: 300000 = 5 min)
  timeout_ms?: number;

  // Whether to return git diff (only applicable if repo is provided)
  include_diff?: boolean;

  // Custom system prompt to append
  system_prompt?: string;

  // Permission mode for Claude Code
  permission_mode?: 'acceptEdits' | 'full' | 'restricted';

  // Working directory within the sandbox
  working_dir?: string;
}

/**
 * Request for SDK-based execution via AI Gateway
 */
export interface SDKExecuteRequest {
  // The prompt to send to Claude
  prompt: string;

  // Optional: Instance ID for multi-tenant scenarios
  instance_id?: string;

  // Optional: Project ID for tracking
  project_id?: string;

  // Optional: Execution options
  options?: SDKExecuteOptions;
}

/**
 * Options for SDK-based execution via AI Gateway
 */
export interface SDKExecuteOptions {
  // Maximum tokens in response (default: 1024)
  max_tokens?: number;

  // Model to use (default: 'sonnet')
  // Can be shorthand: 'opus', 'sonnet', 'haiku'
  // Or full model ID: 'claude-sonnet-4-20250514'
  model?: string;

  // Custom system prompt
  system_prompt?: string;
}

/**
 * Response from SDK-based execution via AI Gateway
 */
export interface SDKExecuteResponse {
  success: boolean;
  request_id: string;
  timestamp: string;

  // The result text from Claude
  result?: string;

  // Execution metadata
  metadata?: {
    execution_time_ms: number;
    model?: string;
    usage?: {
      input_tokens: number;
      output_tokens: number;
    };
    stop_reason?: string | null;
  };
}

/**
 * Response from sandbox/CLI task execution
 */
export interface ExecuteResponse {
  success: boolean;
  request_id: string;
  timestamp: string;

  // Execution output
  logs?: string;
  diff?: string;
  result?: string;

  // Execution metadata
  metadata?: {
    execution_time_ms: number;
    sandbox_id: string;
    repo?: string;
  };
}

/**
 * Error response format
 */
export interface ErrorResponse {
  error: string;
  error_code: string;
  request_id: string;
  details?: Record<string, unknown>;
}

/**
 * Health check response
 */
export interface HealthResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  service: string;
  timestamp: string;
  version?: string;
}

/**
 * Command execution result from sandbox
 */
export interface CommandResult {
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode?: number;
}
